# Generated by Django 4.0.10 on 2024-07-09 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('offer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('discount', models.IntegerField()),
                ('item_quantity', models.IntegerField()),
                ('free_item_quantity', models.IntegerField()),
                ('free_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_item_id', to='menu.menuitem')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id', to='menu.menuitem')),
            ],
            options={
                'db_table': 'fd_offers',
            },
        ),
    ]
