# Generated by Django 5.0.2 on 2024-07-10 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            name='Offers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('offer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('offer_type', models.CharField(max_length=255)),
                ('discount', models.IntegerField()),
                ('item_quantity', models.IntegerField()),
                ('free_item_quantity', models.IntegerField()),
                ('type', models.CharField(max_length=225)),
                ('is_approved', models.BooleanField(default=0)),
                ('free_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_item_id', to='menu.menuitem')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id', to='menu.menuitem')),
            ],
            options={
                'db_table': 'fd_offers',
            },
        ),
    ]
