# Generated by Django 5.0.2 on 2024-07-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offers_restaurant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='allow_multiple_offers',
            field=models.BooleanField(default=0),
        ),
    ]
