# Generated by Django 5.0.2 on 2024-07-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offers_allow_multiple_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='type',
            field=models.CharField(choices=[('ON_CART', 'on_cart'), ('ON_ITEM', 'on_item')], default='ON_CART', max_length=255),
        ),
    ]
