# Generated by Django 5.0.2 on 2024-07-11 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('offers', '0005_alter_offers_discount_alter_offers_free_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='free_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='free_item_id', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='free_item_quantity',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='offers',
            name='is_approved',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='offers',
            name='item_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_id', to='menu.menuitem'),
        ),
    ]
