# Generated by Django 5.0.2 on 2024-07-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_alter_offers_free_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='is_approved',
            field=models.BooleanField(default=0),
        ),
    ]
