# Generated by Django 5.0.2 on 2024-07-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_pic',
            field=models.ImageField(blank=True, db_column='item_pic', null=True, upload_to='Images/ItemPic'),
        ),
    ]
