# Generated by Django 5.0.2 on 2024-06-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='id',
            new_name='menu_id',
        ),
    ]
