# Generated by Django 4.0.10 on 2024-06-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.BigAutoField(db_column='usr_id', primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('mobile_no', models.CharField(db_column='mobile_number', max_length=50, null=True, unique=True)),
                ('dob', models.DateField(db_column='usr_dob', null=True)),
            ],
            options={
                'db_table': 'fd_customers',
            },
        ),
    ]
