# Generated by Django 4.0.10 on 2024-07-09 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('mobile_no', models.CharField(db_column='mobile_number', max_length=50, null=True, unique=True)),
                ('dob', models.DateField(db_column='usr_dob', null=True)),
                ('credit', models.CharField(default='1000', max_length=255)),
            ],
            options={
                'db_table': 'fd_customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerOTP',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer_otp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=255)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customers')),
            ],
            options={
                'db_table': 'fd_customer_otp',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer_cart_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('menu_item', models.JSONField()),
                ('total_price', models.CharField(default=0, max_length=255)),
                ('is_ordered', models.BooleanField(default=0)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customers')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantprofile')),
            ],
            options={
                'db_table': 'fd_cart',
            },
        ),
    ]
