# Generated by Django 5.0.2 on 2024-06-30 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='menu_items',
            new_name='menu_item',
        ),
    ]
