# Generated by Django 5.0.2 on 2024-07-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_approved',
            field=models.BooleanField(default=0),
        ),
    ]
