# Generated by Django 4.0.10 on 2024-07-10 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offers_allow_multiple_offers'),
        ('customer', '0002_ratinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_offer_applied',
            field=models.BooleanField(default=0),
        ),
        migrations.CreateModel(
            name='OffersHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('offers_history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.cart')),
                ('offers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offers')),
            ],
            options={
                'db_table': 'fd_offers_history',
            },
        ),
    ]
