# Generated by Django 5.0.2 on 2024-07-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_cart_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_approved',
        ),
    ]
