# Generated by Django 5.0.2 on 2024-07-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_menu_items_cart_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.CharField(max_length=255),
        ),
    ]
