# Generated by Django 5.0.2 on 2024-07-19 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_cart_discounted_price'),
        ('restaurant', '0007_alter_restaurantprofile_restaurant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='restaurant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantprofile'),
        ),
    ]
