# Generated by Django 4.2.13 on 2024-06-23 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RestaurantProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "restaurant_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("restaurant_name", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
            options={
                "db_table": "fd_restaurant_profile",
            },
        ),
        migrations.CreateModel(
            name="RestaurantOTP",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "restaurant_otp_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("otp", models.CharField(max_length=255)),
                (
                    "restaurant_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.restaurantprofile",
                    ),
                ),
            ],
            options={
                "db_table": "fd_restaurant_otp",
            },
        ),
    ]
