# Generated by Django 5.0.2 on 2024-06-18 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='restaurant_product_review_average',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='username',
        ),
    ]
