# Generated by Django 5.0.2 on 2024-07-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='operational_status',
            field=models.BooleanField(default=0),
        ),
    ]
