# Generated by Django 4.0.10 on 2024-07-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
