# Generated by Django 5.0.2 on 2024-06-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurantprofile_restaurant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='Restaurant_type',
            field=models.CharField(choices=[('RESTRAUNT', 'Restraunt'), ('FAST_FOOD', 'Fast Food'), ('FAST_CASUAL', 'Fast Casual'), ('CASUAL_DINING', 'Casual Dining'), ('FINE_DINING', 'Fine Dining'), ('CAFE', 'Café or Bistro'), ('BUFFET', 'Buffet'), ('FOOD_TRUCK', 'Food Truck'), ('FAMILY_STYLE', 'Family Style'), ('POP_UP', 'Pop-up Restaurant'), ('ETHNIC', 'Ethnic Restaurant'), ('BRASSERIE', 'Brasserie'), ('PIZZERIA', 'Pizzeria'), ('STEAKHOUSE', 'Steakhouse'), ('SEAFOOD', 'Seafood Restaurant'), ('VEGETARIAN_VEGAN', 'Vegetarian/Vegan Restaurant')], default='RESTRAUNT', max_length=255),
        ),
    ]
