# Generated by Django 4.0.10 on 2024-07-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurantprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='no_of_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
