# Generated by Django 5.0.2 on 2024-07-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurantprofile_no_of_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='Restaurant_pic',
            field=models.ImageField(db_column='profile_pic', null=True, upload_to='Images/ProfilePic'),
        ),
    ]
