# Generated by Django 5.0.2 on 2024-07-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurantprofile_restaurant_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='Restaurant_pic',
            field=models.ImageField(blank=True, db_column='restaurant_pic', null=True, upload_to='Images/RestaurantPic'),
        ),
    ]
